   drop table JAHIA_DX_STATISTICS

   create table JAHIA_DX_STATISTICS (
        pk bigint generated by default as identity (START WITH 1, INCREMENT BY 1),
	      metric_type varchar(255),
	      sitekey varchar(255),
	      metric_timespan varchar(255),
        metric_time timestamp,
        metric bigint not null,
        primary key (pk)
    )

 /* INSERT INTO  */